# Generated by Django 4.2.2 on 2023-06-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовленя', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
